### PR TITLE
Move autotag into config

### LINKED ISSUE #61: Move autotag data into a data file
It shouldn't be hardcoded

_Issue created by Ginger [here](https://chat.stackexchange.com/transcript/106764?m=63514274#63514274)_

### PR DESCRIPTION
**Pull request by GingerIndustries**
Closes #61.

### CODE REVIEW

**Review by Lyxal — CHANGES_REQUESTED** [review]
What if people who can't access the config file need to change the tag map?

**Comment by GingerIndustries** [comment]
> What if people who can't access the config file need to change the tag map?

There are already a few private-config-specific settings (like for !!/prod), so I'm following precendent. Maybe it'd be a good idea to split the config into public and private files?

**Comment by Lyxal** [comment]
> > What if people who can't access the config file need to change the tag map?
> 
> There are already a few private-config-specific settings (like for !!/prod), so I'm following precendent. Maybe it'd be a good idea to split the config into public and private files?

That might be a good idea yes.

**Comment by GingerIndustries** [comment]
> > > What if people who can't access the config file need to change the tag map?
> > 
> > 
> > There are already a few private-config-specific settings (like for !!/prod), so I'm following precendent. Maybe it'd be a good idea to split the config into public and private files?
> 
> That might be a good idea yes.

Split performed

**Review by Lyxal — APPROVED** [review]
Nice

**Pull request merged**
