### PR TITLE
Add close issue command

### PR DESCRIPTION
**Pull request by GenericProgrammer1234**
This command will allow you to close issues, pretty simple.

### CODE REVIEW

**Review by GingerIndustries — CHANGES_REQUESTED** [review]
Only change I'd make to this is making the body argument optional so it's possible to skip leaving a comment (just set it to a default value of `Nome` or some such and check for that when sending the comment); otherwise this looks pretty good!

**Comment by GenericProgrammer1234** [comment]
Nome, interesting, so comment on the administrative division of modern Greece's servers? Got it.

**Comment by GingerIndustries** [comment]
@GenericProgrammer1234 This doesn't actually _check_ for the None value?

**Review by GingerIndustries — CHANGES_REQUESTED** [review]
This doesn't actually _check_ for the `None` value?

**Comment by GingerIndustries** [comment]
> Won't it just treat None as nothing composing the string without the None part or am I being stupid?

If the argument is None it should skip sending the comment request

**Comment by GenericProgrammer1234** [comment]
Oh.

**Review by GingerIndustries — APPROVED** [review]

**Pull request merged**
