### PR TITLE
Don't prefix statuses with "I am doing"

### PR DESCRIPTION
**Pull request by ysthakur**
Currently, all statuses have to start with "I am doing." This is somewhat restrictive and makes for awkward sentences like "I am doing tying my shoelaces"

### CODE REVIEW

**Review by mathcat4 — COMMENTED** [review]
Wouldn't the status start with a lowercase letter now?

**Comment by GingerIndustries** [comment]
You're going to have to go through all the statuses and add "I am doing" to the ones that need it

**Comment by ysthakur** [comment]
Hey, let me finish making the PR before reviewing it (I guess it's my fault for not making it a draft)

**Review by hyper-neutrino — APPROVED** [review]
LGTM

**Pull request merged**
