### PR TITLE
Add juice command

### PR DESCRIPTION
**Pull request by PlaceReporter99**
Buy, sell, and browse the catalog of juices!

Fixes issue #41.

### CODE REVIEW

**Review by nayakrujul — APPROVED** [review]
LGTM but I think we should wait for @GingerIndustries's review before merging

**Comment by PlaceReporter99** [comment]
> LGTM but I think we should wait for @GingerIndustries's review before merging

Yes they are the owner.

**Comment by PlaceReporter99** [comment]
@nayakrujul would i also need to add to the command regex?

**Comment by nayakrujul** [comment]
@PlaceReporter99 probably, but I haven't done much of this either, so I'm not too sure. @GingerIndustries can tell you though.

**Comment by GingerIndustries** [comment]
I'm on vacation right now, will review when I get back.

**Comment by PlaceReporter99** [comment]
@GingerIndustries I hope you have a nice vacation!

**Comment by PlaceReporter99** [comment]
@nayakrujul since i made a few more commits I've re-requested review.

**Review by nayakrujul — APPROVED** [review]
LGTM, good work @PlaceReporter99

**Comment by PlaceReporter99** [comment]
@GingerIndustries can you review this?

**Comment by GingerIndustries** [comment]
I have a better idea for the juice system, which I will be implementing soon(tm). Closing this for now.

**Comment by PlaceReporter99** [comment]
@GingerIndustries `soon => not_soon`

**Pull request closed without merging**
